### ISSUE TITLE
Private package list

### ISSUE THREAD

**Issue by Sam-Burns** [spryker/rabbit-mq#5]
Is this repo in the private Packagist at https://code.spryker.com/repo/private , like all the others?  We've been having some issues cloning it on build servers today

**Comment by hhebbo** [comment]
Hi @Sam-Burns,

Yes, it is in code.spryker.com/repo/private. What are the issues?

**Comment by Sam-Burns** [comment]
Thank you. Might just be having issues with Composer today, because of the issues with the Github API this afternoon.

Thanks for your help.
